import {HomeSafetyChecklistFormData} from "./ApiResponse";

export function mapApiResponseToFormData(responseData: HomeSafetyChecklistFormData)  {
    return {
        staff_id: responseData.staff_id,
        uuid: responseData.uuid,
        completion_percentage: responseData.completion_percentage,
        client_name: responseData.client_name,
        participant_name: responseData.participant_name,
        address: responseData.address,
        phone: responseData.phone,
        email: responseData.email,
        is_new_participant: responseData.is_new_participant,
        is_review_existing: responseData.is_review_existing,
        does_participant_agree: responseData.does_participant_agree,
        entry_door: responseData.entry_door,
        entry_door_other: responseData.entry_door_other,
        form_status: responseData.form_status || '',
        submit_final: responseData.submit_final ?? 0,


        parking_adequate: responseData.outside_entry?.parking_adequate,
        parking_adequate_strategy: responseData.outside_entry?.parking_adequate_strategy,
        pathway_surface: responseData.outside_entry?.pathway_surface,
        pathway_surface_strategy: responseData.outside_entry?.pathway_surface_strategy,
        gates_entry_easy: responseData.outside_entry?.gates_entry_easy,
        gates_entry_easy_strategy: responseData.outside_entry?.gates_entry_easy_strategy,
        lighting_adequate: responseData.outside_entry?.lighting_adequate,
        lighting_adequate_strategy: responseData.outside_entry?.lighting_adequate_strategy,
        outdoor_fire_hazards: responseData.outside_entry?.outdoor_fire_hazards,
        outdoor_fire_hazards_strategy: responseData.outside_entry?.outdoor_fire_hazards_strategy,


        exit_doors_unobstructed: responseData.inside_residence?.exit_doors_unobstructed,
        exit_doors_unobstructed_strategy: responseData.inside_residence?.exit_doors_unobstructed_strategy,
        heaters_suitable: responseData.inside_residence?.heaters_suitable,
        heaters_suitable_strategy: responseData.inside_residence?.heaters_suitable_strategy,
        aids_equipment_condition: responseData.inside_residence?.aids_equipment_condition,
        aids_equipment_condition_strategy: responseData.inside_residence?.aids_equipment_condition_strategy,
        evidence_of_pests: responseData.inside_residence?.evidence_of_pests,
        evidence_of_pests_strategy: responseData.inside_residence?.evidence_of_pests_strategy,
        participant_open_door: responseData.inside_residence?.participant_open_door,
        participant_open_door_strategy: responseData.inside_residence?.participant_open_door_strategy,
        fire_hazards: responseData.inside_residence?.fire_hazards,
        fire_hazards_strategy: responseData.inside_residence?.fire_hazards_strategy,
        vacuum_cleaner_ok: responseData.inside_residence?.vacuum_cleaner_ok,
        vacuum_cleaner_ok_strategy: responseData.inside_residence?.vacuum_cleaner_ok_strategy,
        mop_bucket_ok: responseData.inside_residence?.mop_bucket_ok,
        mop_bucket_ok_strategy: responseData.inside_residence?.mop_bucket_ok_strategy,
        step_ladder_ok: responseData.inside_residence?.step_ladder_ok,
        step_ladder_ok_strategy: responseData.inside_residence?.step_ladder_ok_strategy,
        cleaning_substances_ok: responseData.inside_residence?.cleaning_substances_ok,
        cleaning_substances_ok_strategy: responseData.inside_residence?.cleaning_substances_ok_strategy,



        hallways_lounge_dining_bedroom: responseData.hallways?.hallways_lounge_dining_bedroom,
        hallways_lounge_dining_bedroom_strategy: responseData.hallways?.hallways_lounge_dining_bedroom_strategy,
        pests_evidence: responseData.hallways?.pests_evidence,
        pests_evidence_strategy: responseData.hallways?.pests_evidence_strategy,
        lighting_workspace: responseData.hallways?.lighting_workspace,
        lighting_workspace_strategy: responseData.hallways?.lighting_workspace_strategy,
        furniture_stable: responseData.hallways?.furniture_stable,
        furniture_stable_strategy: responseData.hallways?.furniture_stable_strategy,
        bed_adjustable: responseData.hallways?.bed_adjustable,
        bed_adjustable_strategy: responseData.hallways?.bed_adjustable_strategy,
        electrical_switches: responseData.hallways?.electrical_switches,
        electrical_switches_strategy: responseData.hallways?.electrical_switches_strategy,
        private_sleep_space: responseData.hallways?.private_sleep_space,
        private_sleep_space_strategy: responseData.hallways?.private_sleep_space_strategy,
        hallways_fire_hazards: responseData.hallways?.hallways_fire_hazards,
        hallways_fire_hazards_strategy: responseData.hallways?.hallways_fire_hazards_strategy,


        floor_condition: responseData.hallways_safety_assessment?.floor_condition,
        floor_condition_strategy: responseData.hallways_safety_assessment?.floor_condition_strategy,
        electrical_condition: responseData.hallways_safety_assessment?.electrical_condition,
        electrical_condition_strategy: responseData.hallways_safety_assessment?.electrical_condition_strategy,
        ventilation_condition: responseData.hallways_safety_assessment?.ventilation_condition,
        ventilation_condition_strategy: responseData.hallways_safety_assessment?.ventilation_condition_strategy,
        bench_condition: responseData.hallways_safety_assessment?.bench_condition,
        bench_condition_strategy: responseData.hallways_safety_assessment?.bench_condition_strategy,
        stove_condition: responseData.hallways_safety_assessment?.stove_condition,
        stove_condition_strategy: responseData.hallways_safety_assessment?.stove_condition_strategy,
        fridge_condition: responseData.hallways_safety_assessment?.fridge_condition,
        fridge_condition_strategy: responseData.hallways_safety_assessment?.fridge_condition_strategy,
        bath_access: responseData.hallways_safety_assessment?.bath_access,
        bath_access_strategy: responseData.hallways_safety_assessment?.bath_access_strategy,
        toilet_access: responseData.hallways_safety_assessment?.toilet_access,
        toilet_access_strategy: responseData.hallways_safety_assessment?.toilet_access_strategy,
        privacy_condition: responseData.hallways_safety_assessment?.privacy_condition,
        privacy_condition_strategy: responseData.hallways_safety_assessment?.privacy_condition_strategy,
        laundry_condition: responseData.hallways_safety_assessment?.laundry_condition,
        laundry_condition_strategy: responseData.hallways_safety_assessment?.laundry_condition_strategy,
        ironing_condition: responseData.hallways_safety_assessment?.ironing_condition,
        ironing_condition_strategy: responseData.hallways_safety_assessment?.ironing_condition_strategy,
        manual_handling_risks: responseData.hallways_safety_assessment?.manual_handling_risks,
        manual_handling_strategy: responseData.hallways_safety_assessment?.manual_handling_strategy,
        kitchen_fire_hazards: responseData.hallways_safety_assessment?.kitchen_fire_hazards,
        kitchen_fire_hazards_strategy: responseData.hallways_safety_assessment?.kitchen_fire_hazards_strategy,


        outside_paths_veranda_steps: responseData.outside_residence_assessment?.outside_paths_veranda_steps,
        outside_paths_veranda_steps_strategy: responseData.outside_residence_assessment?.outside_paths_veranda_steps_strategy,
        outside_pets_restrained: responseData.outside_residence_assessment?.outside_pets_restrained,
        outside_pets_restrained_strategy: responseData.outside_residence_assessment?.outside_pets_restrained_strategy,
        outside_lighting_adequate: responseData.outside_residence_assessment?.outside_lighting_adequate,
        outside_lighting_adequate_strategy: responseData.outside_residence_assessment?.outside_lighting_adequate_strategy,
        outside_door_easy_open: responseData.outside_residence_assessment?.outside_door_easy_open,
        outside_door_easy_open_strategy: responseData.outside_residence_assessment?.outside_door_easy_open_strategy,
        outside_lawn_mower_condition: responseData.outside_residence_assessment?.outside_lawn_mower_condition,
        outside_lawn_mower_condition_strategy: responseData.outside_residence_assessment?.outside_lawn_mower_condition_strategy,
        outside_electrical_condition: responseData.outside_residence_assessment?.outside_electrical_condition,
        outside_electrical_condition_strategy: responseData.outside_residence_assessment?.outside_electrical_condition_strategy,
        outside_fire_hazards: responseData.outside_residence_assessment?.outside_fire_hazards,
        outside_fire_hazards_strategy: responseData.outside_residence_assessment?.outside_fire_hazards_strategy,



        misc_children_living_at_home: responseData.miscellaneous?.misc_children_living_at_home,
        misc_children_living_at_home_strategy: responseData.miscellaneous?.misc_children_living_at_home_strategy,
        misc_weapons_stored_appropriately: responseData.miscellaneous?.misc_weapons_stored_appropriately,
        misc_weapons_stored_appropriately_strategy: responseData.miscellaneous?.misc_weapons_stored_appropriately_strategy,
        misc_smoking_outside_only: responseData.miscellaneous?.misc_smoking_outside_only,
        misc_smoking_outside_only_strategy: responseData.miscellaneous?.misc_smoking_outside_only_strategy,
        misc_mobility_issues: responseData.miscellaneous?.misc_mobility_issues,
        misc_mobility_issues_strategy: responseData.miscellaneous?.misc_mobility_issues_strategy,
        misc_equipment_good_condition: responseData.miscellaneous?.misc_equipment_good_condition,
        misc_equipment_good_condition_strategy: responseData.miscellaneous?.misc_equipment_good_condition_strategy,
        misc_ppe_requirements: responseData.miscellaneous?.misc_ppe_requirements,
        misc_ppe_requirements_strategy: responseData.miscellaneous?.misc_ppe_requirements_strategy,
        misc_personal_threats: responseData.miscellaneous?.misc_personal_threats,
        misc_personal_threats_strategy: responseData.miscellaneous?.misc_personal_threats_strategy,
        misc_safe_neighbourhood: responseData.miscellaneous?.misc_safe_neighbourhood,
        misc_safe_neighbourhood_strategy: responseData.miscellaneous?.misc_safe_neighbourhood_strategy,
        misc_aggression_in_home: responseData.miscellaneous?.misc_aggression_in_home,
        misc_aggression_in_home_strategy: responseData.miscellaneous?.misc_aggression_in_home_strategy,



        residence_house_type: responseData.residence_type?.residence_house_type,
        residence_other_type: responseData.residence_type?.residence_other_type,
        assessment_completed_with: responseData.residence_type?.assessment_completed_with,
        name: responseData.residence_type?.name,
        position: responseData.residence_type?.position,
        review_date: responseData.residence_type?.review_date,
        care_facility: responseData.residence_type?.care_facility


    };
}