const AgreementFormaData = {
    participant_name: '',
    ndis_number: '',
    address: '',
    contact: '',
    email: '',
    dob: '',
    ndis_plan_start_date: '',
    ndis_plan_end_date: '',
    term_start_date: '',
    term_end_date: '',
    term_of_this_agreement: '',
    area_of_support: [],
    representative_name: '',
    representative_relationship: '',
    representative_contact: '',
    representative_email: '',
    submit_final: 0,
    form_status: '',


    accepted_name: '',
    accepted_position: '',
    accepted_signature: '',
    accepted_date: '',
    consents_participant_name: '',
    participant_role: '',
    participant_signature: '',
    participant_date: '',
    witness_name: '',
    witness_signature: '',
    witness_date: '',
    verbal_staff_name: '',
    verbal_staff_signature: '',
    verbal_staff_position: '',
    verbal_date: '',
    other_notes: '',
    received_signed_copy: '',
    agreed_verbally: '',
    cms_comments_entered: '',
}

export default AgreementFormaData;