// maps API response data to formData shape
import { SupportApiResponse } from '@/src/components/SupportPlan/ApiResponse';

export function mapApiResponseToFormData(responseData: SupportApiResponse) {
  return {
    effective_date: responseData.effective_date || '',
    review_date: responseData.review_date || '',
    confirmation_date: responseData.confirmation_date || '',
    developed_by: responseData.developed_by || '',
    invited_but_not_participated: responseData.invited_but_not_participated || '',
    participant_name: responseData.approval?.participant_name || '',
    date_of_approval: responseData.approval?.date_of_approval || '',
    signature: responseData.approval?.signature || '',
    support_representative_name: responseData.representative_approval?.support_representative_name || '',
    role: responseData.representative_approval?.role || '',
    date_of_approval_representative: responseData.representative_approval?.date_of_approval || '',
    care_partner_name: responseData.care_approval?.care_partner_name || '',
    care_partner_role: responseData.care_approval?.care_partner_role || '',
    care_partner_contact_phone: responseData.care_approval?.care_partner_contact_phone || '',
    care_partner_email: responseData.care_approval?.care_partner_email || '',
    form_status: responseData.form_status || '',
    submit_final: responseData.submit_final ?? 0,

    // Keep in Touch fields
    need_help_to_communicate: responseData.keep_in_touch?.need_help_to_communicate ?? 0,
    type_of_difficulty: responseData.keep_in_touch?.type_of_difficulty || '',
    contact_first_instance: responseData.keep_in_touch?.contact_first_instance ?? 0, 
    details: responseData.keep_in_touch?.details || '',
    language_spoken: responseData.keep_in_touch?.language_spoken || '',
    use_nrs: responseData.keep_in_touch?.use_nrs ?? 0,
    require_interpreter: responseData.keep_in_touch?.require_interpreter ?? 0,
    written: responseData.keep_in_touch?.written || '',
    verbal: responseData.keep_in_touch?.verbal || '',
    schedule_change_notification: responseData.keep_in_touch?.schedule_change_notification || '',
    interpreter_arrangement: responseData.keep_in_touch?.interpreter_arrangement || '',
    financial_statement_method: responseData.keep_in_touch?.financial_statement_method || '',
    feedback_survey_method: responseData.keep_in_touch?.feedback_survey_method || '',
    marketing_material_method: responseData.keep_in_touch?.marketing_material_method || '',
    preferred_communication_method: responseData.keep_in_touch?.preferred_communication_method || '',
    join_cab: responseData.keep_in_touch?.join_cab ?? 0,

    // NonResponsive fields
    telephone_home_or_mobile: responseData.non_responsive?.telephone_home_or_mobile ?? 0,
    telephone_details: responseData.non_responsive?.telephone_details || '',

    contact_emergency_contact: responseData.non_responsive?.contact_emergency_contact ?? 0,
    emergency_contact_details: responseData.non_responsive?.emergency_contact_details || '',

    access_spare_key: responseData.non_responsive?.access_spare_key ?? 0,
    enter_home_with_spare_key: responseData.non_responsive?.enter_home_with_spare_key ?? 0,
    spare_key_details: responseData.non_responsive?.spare_key_details || '',

    contact_other_persons: responseData.non_responsive?.contact_other_persons ?? 0,
    other_persons_details: responseData.non_responsive?.other_persons_details || '',

    contact_police_if_no_key: responseData.non_responsive?.contact_police_if_no_key ?? 0,
    police_contact_details: responseData.non_responsive?.police_contact_details || '',

    access_key_lock: responseData.non_responsive?.access_key_lock ?? 0,
    key_lock_code: responseData.non_responsive?.key_lock_code || '',
    key_lock_details: responseData.non_responsive?.key_lock_details || '',


    //particpant details

    first_name: responseData.participant_detail?.first_name ?? '',
    surname: responseData.participant_detail?.surname || '',
    preferred_name: responseData.participant_detail?.preferred_name || '',
    date_of_birth: responseData.participant_detail?.date_of_birth || '',
    country_of_birth: responseData.participant_detail?.country_of_birth || '',
    identify_as_aboriginal_or_torres_strait: responseData.participant_detail?.identify_as_aboriginal_or_torres_strait ?? 0,
    gender: responseData.participant_detail?.gender || '',

    //contact details

    phone: responseData.contact_detail?.phone || '',
    address: responseData.contact_detail?.address || '',
    is_rural_area: responseData.contact_detail?.is_rural_area ?? 0,
    mailing_address: responseData.contact_detail?.mailing_address || '',
    email: responseData.contact_detail?.email || '',
    
    //secondary contact details

    secondary_role: responseData.contact_detail_secondary?.secondary_role || '',
    secondary_phone: responseData.contact_detail_secondary?.secondary_phone || '',
    secondary_email: responseData.contact_detail_secondary?.secondary_email || '',
    secondary_address: responseData.contact_detail_secondary?.secondary_address || '',
    secondary_best_time_to_contact: responseData.contact_detail_secondary?.secondary_best_time_to_contact || '',
    secondary_is_mac_registered: responseData.contact_detail_secondary?.secondary_is_mac_registered ?? 0,
    secondary_list_documents: responseData.contact_detail_secondary?.secondary_list_documents || '',
    secondary_legal_documentation_stored: responseData.contact_detail_secondary?.secondary_legal_documentation_stored ?? 0,
    secondary_date_legal_orders_end: responseData.contact_detail_secondary?.secondary_date_legal_orders_end || '',
    secondary_participants_agreed_contact: responseData.contact_detail_secondary?.secondary_participants_agreed_contact ?? 0,
    secondary_participants_agreed_contact_date: responseData.contact_detail_secondary?.secondary_participants_agreed_contact_date || '',
    secondary_decision_making_approval_for: responseData.contact_detail_secondary?.secondary_decision_making_approval_for || '',


    // Funding details
    aged_care_id: responseData.support_funding?.aged_care_id || '',
    pension_status: responseData.support_funding?.pension_status || '',
    pension_card_details: responseData.support_funding?.pension_card_details || '',
    card_number: responseData.support_funding?.card_number || '',
    card_expiry: responseData.support_funding?.card_expiry || '',
    approved_funding_level: responseData.support_funding?.approved_funding_level || '',
    awaiting_package_upgrade: responseData.support_funding?.awaiting_package_upgrade ?? 0,
    upgrade_details: responseData.support_funding?.upgrade_details || '',
    has_chsp_referral_codes: responseData.support_funding?.has_chsp_referral_codes ?? 0,
    chsp_referral_details: responseData.support_funding?.chsp_referral_details || '',
    war_veteran_or_widow: responseData.support_funding?.war_veteran_or_widow ?? 0,
    dva_number: responseData.support_funding?.dva_number || '',
    medicare_number: responseData.support_funding?.medicare_number || '',
    private_health_insurance: responseData.support_funding?.private_health_insurance || '',
    hcp_funding_level: responseData.support_funding?.hcp_funding_level || '',
    has_companion_card: responseData.support_funding?.has_companion_card ?? 0,

    // Support Plan Services
    services: responseData.services.map(service => ({
      name: service.name || '',
      service_provided: service.service_provided || '',
      funded_by: service.funded_by || '',
      duration_frequency: service.duration_frequency || '',
      support_to_implement_by_us: service.support_to_implement_by_us ? 1 : 0,
      goal_key: service.goal_key || ''
    })),


    // Employee Matching Needs
    cultural_considerations: responseData.supportplan_employee?.cultural_considerations || '',
    specific_training_required: responseData.supportplan_employee?.specific_training_required || '',
    common_interests: responseData.supportplan_employee?.common_interests || '',

    // My Goals
    my_goals: responseData.my_goals.map(goal => ({
      goal: goal.goal || '',
      measure_progress: goal.measure_progress || '',
      success_look_like: goal.success_look_like || '',
      who_will_support: goal.who_will_support || '',
      participant_support: goal.participant_support || '',
      target_date: goal.target_date || '',
      goal_key: goal.goal_key || ''
    })),


    // Living Arrangements
    reside_in: responseData.living_arrangement?.reside_in || '',
    reside_with: responseData.living_arrangement?.reside_with || '',
    home_safety_assessment_date: responseData.living_arrangement?.home_safety_assessment_date || '',
    is_home_suitable: responseData.living_arrangement?.is_home_suitable ?? 0,
    home_suitable_details: responseData.living_arrangement?.home_suitable_details || '',
    at_risk_of_homelessness: responseData.living_arrangement?.at_risk_of_homelessness ?? 0,
    homelessness_details: responseData.living_arrangement?.homelessness_details || '',


    // Cultural Diversities
    is_lgbti: responseData.cultural_diversity	?.is_lgbti ?? 0,
    lgbti_details: responseData.cultural_diversity	?.lgbti_details || '',
    is_separated_family: responseData.cultural_diversity	?.is_separated_family ?? 0,
    separated_family_details: responseData.cultural_diversity	?.separated_family_details || '',
    has_cultural_events: responseData.cultural_diversity	?.has_cultural_events ?? 0,
    cultural_events_details: responseData.cultural_diversity	?.cultural_events_details || '',
    has_past_events: responseData.cultural_diversity	?.has_past_events ?? 0,
    past_events_details: responseData.cultural_diversity	?.past_events_details || '',
    has_non_disclosure_items: responseData.cultural_diversity	?.has_non_disclosure_items ?? 0,
    non_disclosure_details: responseData.cultural_diversity	?.non_disclosure_details || '',



    // General Health
    gp_visit_frequency: responseData.general_health?.gp_visit_frequency || '',
    admitted_hospital_last12months: responseData.general_health?.admitted_hospital_last12months ?? 0,
    admitted_hospital_details: responseData.general_health?.admitted_hospital_details || '',
    preferred_hospital: responseData.general_health?.preferred_hospital ?? 0,
    preferred_hospital_details: responseData.general_health?.preferred_hospital_details || '',
    diagnosis_medication_conditions: responseData.general_health?.diagnosis_medication_conditions || '',
    previous_surgeries: responseData.general_health?.previous_surgeries || '',
    has_allergies: responseData.general_health?.has_allergies ?? 0,
    allergy_details: responseData.general_health?.allergy_details || '',
    health_impact_scale: responseData.general_health?.health_impact_scale ?? 0,
    painful_day_to_day: responseData.general_health?.painful_day_to_day ?? 0,
    painful_day_to_day_details: responseData.general_health?.painful_day_to_day_details || '',
    weight_loss_last3months: responseData.general_health?.weight_loss_last3months ?? 0,
    weight_loss_details: responseData.general_health?.weight_loss_details || '',
    nutritional_concerns: responseData.general_health?.nutritional_concerns ?? 0,
    nutritional_concerns_details: responseData.general_health?.nutritional_concerns_details || '',
    current_weight: responseData.general_health?.current_weight || '',
    annual_vaccinations: responseData.general_health?.annual_vaccinations ?? 0,
    annual_vaccination_details: responseData.general_health?.annual_vaccination_details || '',
    last_influenza_vaccine: responseData.general_health?.last_influenza_vaccine || '',
    last_covid19_vaccine: responseData.general_health?.last_covid19_vaccine || '',
    last_pneumonia_vaccine: responseData.general_health?.last_pneumonia_vaccine || '',
    sleep_difficulties: responseData.general_health?.sleep_difficulties ?? 0,
    sleep_difficulties_details: responseData.general_health?.sleep_difficulties_details || '',
    sleep_routine: responseData.general_health?.sleep_routine || '',
    sleep_routine_worries: responseData.general_health?.sleep_routine_worries ?? 0,
    sleep_routine_worries_details: responseData.general_health?.sleep_routine_worries_details || '',
    alcohol_smoke_drug_use: responseData.general_health?.alcohol_smoke_drug_use ?? 0,
    alcohol_smoke_drug_details: responseData.general_health?.alcohol_smoke_drug_details || '',
    alcohol_smoke_drug_worries: responseData.general_health?.alcohol_smoke_drug_worries ?? 0,
    alcohol_smoke_drug_worries_details: responseData.general_health?.alcohol_smoke_drug_worries_details || '',
    referral_required: responseData.general_health?.referral_required ?? 0,
    referral_required_details: responseData.general_health?.referral_required_details || '',


    // Medication Management
    takes_regular_medications: responseData.medication_management?.takes_regular_medications ?? 0,
    medication_details: responseData.medication_management?.medication_details || '',
    medication_form: responseData.medication_management?.medication_form || '',
    medication_packaging: responseData.medication_management?.medication_packaging || '',
    medications_locked: responseData.medication_management?.medications_locked ?? 0,
    medications_locked_details: responseData.medication_management?.medications_locked_details || '',
    specific_storage_requirements: responseData.medication_management?.specific_storage_requirements || '',
    scheduled_4_or_8_medications: responseData.medication_management?.scheduled_4_or_8_medications ?? 0,
    scheduled_medications_details: responseData.medication_management?.scheduled_medications_details || '',
    chemical_restraint_medications: responseData.medication_management?.chemical_restraint_medications ?? 0,
    takes_more_than_prescribed: responseData.medication_management?.takes_more_than_prescribed ?? 0,
    takes_more_than_prescribed_details: responseData.medication_management?.takes_more_than_prescribed_details || '',
    at_risk_of_missing_medication: responseData.medication_management?.at_risk_of_missing_medication ?? 0,
    missing_medication_details: responseData.medication_management?.missing_medication_details || '',
    able_to_explain_purpose: responseData.medication_management?.able_to_explain_purpose ?? 0,
    last_medication_review_date: responseData.medication_management?.last_medication_review_date || '',
    medication_collection_delivery_details: responseData.medication_management?.medication_collection_delivery_details || '',
    needs_support_with_medication: responseData.medication_management?.needs_support_with_medication ?? 0,
    support_with_medication_details: responseData.medication_management?.support_with_medication_details || '',
    medication_management_worries: responseData.medication_management?.medication_management_worries ?? 0,
    medication_management_worries_details: responseData.medication_management?.medication_management_worries_details || '',
    medication_service_required: responseData.medication_management?.medication_service_required ?? 0,
    support_worker_prompt: responseData.medication_management?.support_worker_prompt ?? 0,


    // Mobility & Transfers
    can_walk_independently: responseData.mobility_transfer?.can_walk_independently ?? 0,
    walk_independently_details: responseData.mobility_transfer?.walk_independently_details || '',
    needs_transfer_support: responseData.mobility_transfer?.needs_transfer_support ?? 0,
    primary_equipment_used: responseData.mobility_transfer?.primary_equipment_used || '',
    can_climb_stairs: responseData.mobility_transfer?.can_climb_stairs ?? 0,
    climb_stairs_details: responseData.mobility_transfer?.climb_stairs_details || '',
    has_stairs_at_home: responseData.mobility_transfer?.has_stairs_at_home ?? 0,
    stairs_at_home_details: responseData.mobility_transfer?.stairs_at_home_details || '',
    can_transfer_self: responseData.mobility_transfer?.can_transfer_self ?? 0,
    transfer_self_details: responseData.mobility_transfer?.transfer_self_details || '', // NEW FIELD
    can_transfer_in_other_envs: responseData.mobility_transfer?.can_transfer_in_other_envs ?? 0,
    transfer_other_env_details: responseData.mobility_transfer?.transfer_other_env_details || '', // NEW FIELD
    uses_bed_pole_or_rails: responseData.mobility_transfer?.uses_bed_pole_or_rails ?? 0,
    bed_pole_prescribed_by_ot: responseData.mobility_transfer?.bed_pole_prescribed_by_ot ?? 0,
    can_access_places_outside_walking_distance: responseData.mobility_transfer?.can_access_places_outside_walking_distance ?? 0,
    access_places_details: responseData.mobility_transfer?.access_places_details || '',
    safe_to_mobilise_in_yard: responseData.mobility_transfer?.safe_to_mobilise_in_yard ?? 0,
    mobilise_yard_details: responseData.mobility_transfer?.mobilise_yard_details || '',
    community_access: responseData.mobility_transfer?.community_access || '',
    drives: responseData.mobility_transfer?.drives ?? 0,
    medications_or_conditions_risk: responseData.mobility_transfer?.medications_or_conditions_risk ?? 0,
    driving_risk_details: responseData.mobility_transfer?.driving_risk_details || '',
    mobility_equipment: responseData.mobility_transfer?.mobility_equipment || '',
    equipment_purchase_type: responseData.mobility_transfer?.equipment_purchase_type || '',
    uses_four_wheel_walker: responseData.mobility_transfer?.uses_four_wheel_walker ?? 0,
    four_wheel_walker_details: responseData.mobility_transfer?.four_wheel_walker_details || '',
    wheelchair_type: responseData.mobility_transfer?.wheelchair_type ?? 0,
    wheelchair_use_details: responseData.mobility_transfer?.wheelchair_use_details || '', // NEW FIELD
    wheelchair_operation: responseData.mobility_transfer?.wheelchair_operation || '',
    wheelchair_ot_recommended: responseData.mobility_transfer?.wheelchair_ot_recommended ?? 0,
    wheelchair_ot: responseData.mobility_transfer?.wheelchair_ot || '', // NEW FIELD
    can_charge_wheelchair: responseData.mobility_transfer?.can_charge_wheelchair ?? 0,
    can_charge_details: responseData.mobility_transfer?.can_charge_details || '', // NEW FIELD
    last_wheelchair_service_date: responseData.mobility_transfer?.last_wheelchair_service_date || '',
    can_carry_5kg: responseData.mobility_transfer?.can_carry_5kg ?? 0,
    carry_5kg_details: responseData.mobility_transfer?.carry_5kg_details || '',
    foot_problems: responseData.mobility_transfer?.foot_problems ?? 0,
    foot_problems_details: responseData.mobility_transfer?.foot_problems_details || '',
    mobility_worries: responseData.mobility_transfer?.mobility_worries ?? 0,
    mobility_worries_details: responseData.mobility_transfer?.mobility_worries_details || '',
    last_ot_assessment_date: responseData.mobility_transfer?.last_ot_assessment_date || '',
    new_ot_referral_required: responseData.mobility_transfer?.new_ot_referral_required ?? 0,
    new_ot_referral_details: responseData.mobility_transfer?.new_ot_referral_details || '', // NEW FIELD
    demmi_assessment_required: responseData.mobility_transfer?.demmi_assessment_required ?? 0,
    demmi_assessment_result: responseData.mobility_transfer?.demmi_assessment_result || '',
    recent_falls: responseData.falls_risk?.recent_falls ?? 0,
    recent_falls_details: responseData.falls_risk?.recent_falls_details || '',
    strategies_to_reduce_risk: responseData.falls_risk?.strategies_to_reduce_risk ?? 0,
    strategies_details: responseData.falls_risk?.strategies_details || '',
    has_safety_pendant: responseData.falls_risk?.has_safety_pendant ?? 0,
    safety_pendant_details: responseData.falls_risk?.safety_pendant_details || '',
    worried_about_falling: responseData.falls_risk?.worried_about_falling ?? 0,
    worried_details: responseData.falls_risk?.worried_details || '',
    referral_falls_clinic: responseData.falls_risk?.referral_falls_clinic ?? 0,
    referral_falls_clinic_details: responseData.falls_risk?.referral_falls_clinic_details || '',
    referral_ot: responseData.falls_risk?.referral_ot ?? 0,
    fallrisk_referral_ot_details: responseData.falls_risk?.fallrisk_referral_ot_details || '',
    referral_physio: responseData.falls_risk?.referral_physio ?? 0,
    referral_physio_details: responseData.falls_risk?.referral_physio_details || '',


    // Cognitions
    cognitive_concerns: responseData.cognition?.cognitive_concerns ?? 0,
    cognitive_concerns_details: responseData.cognition?.cognitive_concerns_details || '',
    diagnosis_dementia: responseData.cognition?.diagnosis_dementia ?? 0,
    diagnosis_dementia_details: responseData.cognition?.diagnosis_dementia_details || '',
    capable_of_decisions: responseData.cognition?.capable_of_decisions ?? 0,
    capable_of_decisions_details: responseData.cognition?.capable_of_decisions_details || '',
    has_power_of_attorney: responseData.cognition?.has_power_of_attorney ?? 0,
    power_of_attorney_details: responseData.cognition?.power_of_attorney_details || '',
    becomes_confused: responseData.cognition?.becomes_confused ?? 0,
    becomes_confused_details: responseData.cognition?.becomes_confused_details || '',
    experienced_delirium: responseData.cognition?.experienced_delirium ?? 0,
    experienced_delirium_details: responseData.cognition?.experienced_delirium_details || '',
    anxious_or_worry: responseData.cognition?.anxious_or_worry ?? 0,
    anxious_or_worry_details: responseData.cognition?.anxious_or_worry_details || '',
    short_term_memory_loss: responseData.cognition?.short_term_memory_loss ?? 0,
    short_term_memory_loss_details: responseData.cognition?.short_term_memory_loss_details || '',
    long_term_memory_loss: responseData.cognition?.long_term_memory_loss ?? 0,
    long_term_memory_loss_details: responseData.cognition?.long_term_memory_loss_details || '',
    atsi_kica_cog_required: responseData.cognition?.atsi_kica_cog_required ?? 0,
    atsi_kica_cog_file: responseData.cognition?.atsi_kica_cog_file || '',
    atsi_kica_carer_required: responseData.cognition?.atsi_kica_carer_required ?? 0,
    atsi_kica_carer_file: responseData.cognition?.atsi_kica_carer_file || '',
    gpcog_required: responseData.cognition?.gpcog_required ?? 0,
    gpcog_file: responseData.cognition?.gpcog_file || '',
    health_literacy_support: responseData.cognition?.health_literacy_support ?? 0,
    health_literacy_support_details: responseData.cognition?.health_literacy_support_details || '',
    gds_required: responseData.cognition?.gds_required ?? 0,
    gds_file: responseData.cognition?.gds_file || '',
    referral_geriatrician: responseData.cognition?.referral_geriatrician ?? 0,
    referral_geriatrician_details: responseData.cognition?.referral_geriatrician_details || '',
    referral_psychologist: responseData.cognition?.referral_psychologist ?? 0,
    referral_psychologist_details: responseData.cognition?.referral_psychologist_details || '',
    referral_psychiatrist: responseData.cognition?.referral_psychiatrist ?? 0,
    referral_psychiatrist_details: responseData.cognition?.referral_psychiatrist_details || '',


    // Behaviour Supports
    feeling_agitation: responseData.behaviour_support?.feeling_agitation ?? 0,
    feeling_agitation_details: responseData.behaviour_support?.feeling_agitation_details || '',
    delusions_hallucinations: responseData.behaviour_support?.delusions_hallucinations ?? 0,
    delusions_hallucinations_details: responseData.behaviour_support?.delusions_hallucinations_details || '',
    personality_changes: responseData.behaviour_support?.personality_changes ?? 0,
    personality_changes_details: responseData.behaviour_support?.personality_changes_details || '',
    wandering_purpose: responseData.behaviour_support?.wandering_purpose ?? 0,
    wandering_purpose_details: responseData.behaviour_support?.wandering_purpose_details || '',
    absconding_concerns: responseData.behaviour_support?.absconding_concerns ?? 0,
    absconding_concerns_details: responseData.behaviour_support?.absconding_concerns_details || '',
    verbal_threats: responseData.behaviour_support?.verbal_threats ?? 0,
    verbal_threats_details: responseData.behaviour_support?.verbal_threats_details || '',
    physical_assault: responseData.behaviour_support?.physical_assault ?? 0,
    physical_assault_details: responseData.behaviour_support?.physical_assault_details || '',
    restrictive_interventions: responseData.behaviour_support?.restrictive_interventions ?? 0,
    restrictive_interventions_details: responseData.behaviour_support?.restrictive_interventions_details || '',
    restrictive_physical: responseData.behaviour_support?.restrictive_physical ?? 0,
    restrictive_approved_by_practitioner: responseData.behaviour_support?.restrictive_approved_by_practitioner ?? 0,
    restrictive_practitioner_details: responseData.behaviour_support?.restrictive_practitioner_details || '',
    current_strategies: responseData.behaviour_support?.current_strategies || '',
    referral_positive_behaviour_practitioner: responseData.behaviour_support?.referral_positive_behaviour_practitioner ?? 0,
    referral_positive_behaviour_practitioner_details: responseData.behaviour_support?.referral_positive_behaviour_practitioner_details || '',
    behaviour_support_plan_required: responseData.behaviour_support?.behaviour_support_plan_required ?? 0,
    behaviour_support_plan_expiry: responseData.behaviour_support?.behaviour_support_plan_expiry || '',

    // Personal Cares
    support_daily_personal_care: responseData.personal_care?.support_daily_personal_care ?? 0,
    daily_personal_care_details: responseData.personal_care?.daily_personal_care_details || '',
    support_showering: responseData.personal_care?.support_showering ?? 0,
    showering_type: responseData.personal_care?.showering_type || '',
    showering_details: responseData.personal_care?.showering_details || '',
    personal_care_routine: responseData.personal_care?.personal_care_routine || '',
    support_dressing: responseData.personal_care?.support_dressing ?? 0,
    dressing_details: responseData.personal_care?.dressing_details || '',
    dressing_routine: responseData.personal_care?.dressing_routine || '',
    equipment_in_bathroom: responseData.personal_care?.equipment_in_bathroom ?? 0,
    equipment_details: responseData.personal_care?.equipment_details || '',
    support_shaving: responseData.personal_care?.support_shaving ?? 0,
    shaving_details: responseData.personal_care?.shaving_details || '',
    support_haircuts: responseData.personal_care?.support_haircuts ?? 0,
    haircuts_details: responseData.personal_care?.haircuts_details || '',
    task_at_home: responseData.personal_care?.task_at_home ?? 0,
    wears_dentures: responseData.personal_care?.wears_dentures ?? 0,
    dentures_details: responseData.personal_care?.dentures_details || '',
    support_teeth_brushing: responseData.personal_care?.support_teeth_brushing ?? 0,
    teeth_brushing_details: responseData.personal_care?.teeth_brushing_details || '',
    ot_bathroom_assessment: responseData.personal_care?.ot_bathroom_assessment ?? 0,
    ot_assessment_type: responseData.personal_care?.ot_assessment_type || '',
    ot_assessment_details: responseData.personal_care?.ot_assessment_details || '',
    referral_ot_required: responseData.personal_care?.referral_ot_required ?? 0,
    plancare_referral_ot_details: responseData.personal_care?.plancare_referral_ot_details || '',
    
    // Continence
    identified_needs: responseData.continence?.identified_needs ?? 0,
    identified_needs_details: responseData.continence?.identified_needs_details || '',

    identify_toilet_needs: responseData.continence?.identify_toilet_needs ?? 0,
    identify_toilet_needs_details: responseData.continence?.identify_toilet_needs_details || '',

    require_prompting: responseData.continence?.require_prompting ?? 0,
    require_prompting_details: responseData.continence?.require_prompting_details || '',

    wears_continence_aids: responseData.continence?.wears_continence_aids ?? 0,
    continence_aids_details: responseData.continence?.continence_aids_details || '',

    ruis_required: responseData.continence?.ruis_required ?? 0,
    ruis_details: responseData.continence?.ruis_details || '',

    rfis_required: responseData.continence?.rfis_required ?? 0,
    rfis_details: responseData.continence?.rfis_details || '',

    funding_for_products: responseData.continence?.funding_for_products ?? 0,
    funding_for_products_details: responseData.continence?.funding_for_products_details || '',

    nurse_assessment: responseData.continence?.nurse_assessment ?? 0,
    nurse_assessment_details: responseData.continence?.nurse_assessment_details || '',

    worry_about_continence: responseData.continence?.worry_about_continence ?? 0,
    worry_about_continence_details: responseData.continence?.worry_about_continence_details || '',


    // Visions
    wears_glasses_or_contacts: responseData.vision?.wears_glasses_or_contacts ?? 0,
    glasses_or_contacts_type: responseData.vision?.glasses_or_contacts_type || '',
    vision_when_worn: responseData.vision?.vision_when_worn || '',
    last_optometrist_appointment: responseData.vision?.last_optometrist_appointment || '',
    vision_worry: responseData.vision?.vision_worry ?? 0,
    vision_worry_details: responseData.vision?.vision_worry_details || '',


    // Hearings
    wears_hearing_devices: responseData.hearing?.wears_hearing_devices ?? 0,
    hearing_devices_details: responseData.hearing?.hearing_devices_details || '',
    when_worn: responseData.hearing?.when_worn || '',
    last_audiologist_appointment: responseData.hearing?.last_audiologist_appointment || '',
    hearing_worry: responseData.hearing?.hearing_worry ?? 0,
    hearing_worry_details: responseData.hearing?.hearing_worry_details || '',

    // Skin Conditions
    has_skin_condition: responseData.skin_condition?.has_skin_condition ?? 0,
    skin_condition_type: responseData.skin_condition?.skin_condition_type || '',
    impacts_daily_activities: responseData.skin_condition?.impacts_daily_activities ?? 0,
    impact_date: responseData.skin_condition?.impact_date || '',
    pain_discomfort_level: responseData.skin_condition?.pain_discomfort_level || '',
    pain_level_score: responseData.skin_condition?.pain_level_score ?? 0,
    management_strategies: responseData.skin_condition?.management_strategies || '',
    skin_condition_worry: responseData.skin_condition?.skin_condition_worry ?? 0,
    worry_date: responseData.skin_condition?.worry_date || '',
    referral_nursing_required: responseData.skin_condition?.referral_nursing_required ?? 0,
    referral_nursing_date: responseData.skin_condition?.referral_nursing_date || '',

    // Dietaries
    intolerances: responseData.dietary?.intolerances ?? 0,
    intolerances_details: responseData.dietary?.intolerances_details || '',
    dysphagia_concerns: responseData.dietary?.dysphagia_concerns ?? 0,
    dysphagia_details: responseData.dietary?.dysphagia_details || '',
    speech_pathologist_recommendations: responseData.dietary?.speech_pathologist_recommendations ?? 0,
    iddsi_food_category: responseData.dietary?.iddsi_food_category || '',
    iddsi_liquid_category: responseData.dietary?.iddsi_liquid_category || '',
    prepares_meals: responseData.dietary?.prepares_meals ?? 0,
    prepares_meals_details: responseData.dietary?.prepares_meals_details || '',
    needs_meal_support: responseData.dietary?.needs_meal_support ?? 0,
    meal_support_details: responseData.dietary?.meal_support_details || '',
    diet_meets_needs: responseData.dietary?.diet_meets_needs ?? 0,
    diet_meets_needs_details: responseData.dietary?.diet_meets_needs_details || '',
    needs_cutting_support: responseData.dietary?.needs_cutting_support ?? 0,
    cutting_support_details: responseData.dietary?.cutting_support_details || '',
    needs_feeding_support: responseData.dietary?.needs_feeding_support ?? 0,
    feeding_support_details: responseData.dietary?.feeding_support_details || '',
    dietician_referral_required: responseData.dietary?.dietician_referral_required ?? 0,
    dietician_referral_details: responseData.dietary?.dietician_referral_details || '',
    needs_shopping_support: responseData.dietary?.needs_shopping_support ?? 0,
    shopping_support_details: responseData.dietary?.shopping_support_details || '',


    // Pain
    ongoing_pain: responseData.pain_management?.ongoing_pain ?? 0,
    pain_details: responseData.pain_management?.pain_details || '',
    pain_location: responseData.pain_management?.pain_location || '',
    pain_frequency: responseData.pain_management?.pain_frequency || '',
    pain_scale: responseData.pain_management?.pain_scale ?? 0,
    supported_for_pain: responseData.pain_management?.supported_for_pain ?? 0,
    supported_pain_details: responseData.pain_management?.supported_pain_details || '',
    pain_management_strategies: responseData.pain_management?.pain_management_strategies || '',
    abbey_pain_scale_required: responseData.pain_management?.abbey_pain_scale_required ?? 0,
    pain_worry: responseData.pain_management?.pain_worry ?? 0,
    pain_worry_details: responseData.pain_management?.pain_worry_details || '',

    feels_lonely: responseData.social_connection?.feels_lonely ?? 0,
    feels_lonely_details: responseData.social_connection?.feels_lonely_details || '',
    has_informal_supports: responseData.social_connection?.has_informal_supports ?? 0,
    informal_supports_details: responseData.social_connection?.informal_supports_details || '',
    wants_more_community_engagement: responseData.social_connection?.wants_more_community_engagement ?? 0,
    community_engagement_details: responseData.social_connection?.community_engagement_details || '',
    wants_support_for_community_engagement: responseData.social_connection?.wants_support_for_community_engagement ?? 0,
    support_for_community_engagement_details: responseData.social_connection?.support_for_community_engagement_details || '',
    needs_community_access_support: responseData.social_connection?.needs_community_access_support ?? 0,
    community_access_support_details: responseData.social_connection?.community_access_support_details || '',
    has_taxi_card: responseData.social_connection?.has_taxi_card ?? 0,
    taxi_card_details: responseData.social_connection?.taxi_card_details || '',
    interested_in_visitors_program: responseData.social_connection?.interested_in_visitors_program ?? 0,
    visitors_program_details: responseData.social_connection?.visitors_program_details || '',
    has_hobbies_activities: responseData.social_connection?.has_hobbies_activities ?? 0,
    hobbies_activities_details: responseData.social_connection?.hobbies_activities_details || '',
    needs_duke_index: responseData.social_connection?.needs_duke_index ?? 0,
    duke_index_details: responseData.social_connection?.duke_index_details || '',
    social_connections_needs_feeding_support: responseData.social_connection?.social_connections_needs_feeding_support ?? 0,
    social_connections_feeding_support_details: responseData.social_connection?.social_connections_feeding_support_details || '',
    social_connections_wants_dietician_referral: responseData.social_connection?.social_connections_wants_dietician_referral ?? 0,
    social_connections_dietician_referral_details: responseData.social_connection?.social_connections_dietician_referral_details || '',
    social_connections_needs_shopping_support: responseData.social_connection?.social_connections_needs_shopping_support ?? 0,
    social_connections_shopping_support_details: responseData.social_connection?.social_connections_shopping_support_details || '',



    needs_domestic_assistance: responseData.home_maintenance?.needs_domestic_assistance ?? 0,
    domestic_assistance_type: responseData.home_maintenance?.domestic_assistance_type || '',
    domestic_assistance_details: responseData.home_maintenance?.domestic_assistance_details || '',
    needs_help_with_cleaning_products: responseData.home_maintenance?.needs_help_with_cleaning_products ?? 0,
    cleaning_products_details: responseData.home_maintenance?.cleaning_products_details || '',
    needs_garden_support: responseData.home_maintenance?.needs_garden_support ?? 0,
    garden_support_details: responseData.home_maintenance?.garden_support_details || '',
    trouble_navigating_at_night: responseData.home_maintenance?.trouble_navigating_at_night ?? 0,
    navigating_at_night_details: responseData.home_maintenance?.navigating_at_night_details || '',
    home_maintenance_worries: responseData.home_maintenance?.home_maintenance_worries ?? 0,
    home_maintenance_worries_details: responseData.home_maintenance?.home_maintenance_worries_details || '',
    last_home_safety_assessment: responseData.home_maintenance?.last_home_safety_assessment || '',
    home_safety_focus_areas: responseData.home_maintenance?.home_safety_focus_areas || '',



    financial_has_power_of_attorney: responseData.financial_support?.financial_has_power_of_attorney ?? 0,
    financial_power_of_attorney_details: responseData.financial_support?.financial_power_of_attorney_details || '',
    has_access_to_money: responseData.financial_support?.has_access_to_money ?? 0,
    access_to_money_details: responseData.financial_support?.access_to_money_details || '',
    at_risk_of_abuse: responseData.financial_support?.at_risk_of_abuse ?? 0,
    risk_of_abuse_details: responseData.financial_support?.risk_of_abuse_details || '',
    needs_support_for_bills: responseData.financial_support?.needs_support_for_bills ?? 0,
    support_for_bills_details: responseData.financial_support?.support_for_bills_details || '',
    not_enough_money: responseData.financial_support?.not_enough_money ?? 0,
    not_enough_money_details: responseData.financial_support?.not_enough_money_details || '',
    support_financial_counsellor: responseData.financial_support?.support_financial_counsellor ?? 0,
    financial_counsellor_details: responseData.financial_support?.financial_counsellor_details || '',
    support_government_initiatives: responseData.financial_support?.support_government_initiatives ?? 0,
    government_initiatives_details: responseData.financial_support?.government_initiatives_details || '',


    // Informal Supports
    is_primary_caregiver: responseData.informal_support?.is_primary_caregiver ?? 0,
    primary_caregiver_details: responseData.informal_support?.primary_caregiver_details || '',
    receiving_help: responseData.informal_support?.receiving_help ?? 0,
    receiving_help_details: responseData.informal_support?.receiving_help_details || '',
    carer_lives_with_you: responseData.informal_support?.carer_lives_with_you ?? 0,
    carer_lives_with_you_details: responseData.informal_support?.carer_lives_with_you_details || '',
    carer_receives_pension: responseData.informal_support?.carer_receives_pension ?? 0,
    carer_pension_details: responseData.informal_support?.carer_pension_details || '',
    factors_affecting_care: responseData.informal_support?.factors_affecting_care ?? 0,
    factors_affecting_care_details: responseData.informal_support?.factors_affecting_care_details || '',
    caregiver_strain_index_required: responseData.informal_support?.caregiver_strain_index_required ?? 0,
    carer_gateway_referral: responseData.informal_support?.carer_gateway_referral ?? 0,
    carer_gateway_referral_details: responseData.informal_support?.carer_gateway_referral_details || '',
    primary_caregiver_receives_allowance: responseData.informal_support?.primary_caregiver_receives_allowance ?? 0,

    // Emergency Readiness
    emergency_at_risk_of_abuse: responseData.emergency_readiness?.emergency_at_risk_of_abuse ?? 0,
    abuse_details: responseData.emergency_readiness?.abuse_details || '',
    opan_referral_required: responseData.emergency_readiness?.opan_referral_required ?? 0,
    opan_referral_details: responseData.emergency_readiness?.opan_referral_details || '',
    risk_of_declining_services: responseData.emergency_readiness?.risk_of_declining_services ?? 0,
    declining_services_details: responseData.emergency_readiness?.declining_services_details || '',
    neglect_indicators: responseData.emergency_readiness?.neglect_indicators ?? 0,
    neglect_indicators_details: responseData.emergency_readiness?.neglect_indicators_details || '',
    emergency_accessible: responseData.emergency_readiness?.emergency_accessible ?? 0,
    emergency_accessible_details: responseData.emergency_readiness?.emergency_accessible_details || '',
    emergency_support_available: responseData.emergency_readiness?.emergency_support_available ?? 0,
    emergency_support_details: responseData.emergency_readiness?.emergency_support_details || '',
    vpr_required: responseData.emergency_readiness?.vpr_required ?? 0,
    vpr_details: responseData.emergency_readiness?.vpr_details || '',


    home_preparation_support: responseData.fire_heat_readiness?.home_preparation_support ?? 0,
    home_preparation_details: responseData.fire_heat_readiness?.home_preparation_details || '',
    hydration_access: responseData.fire_heat_readiness?.hydration_access ?? 0,
    hydration_details: responseData.fire_heat_readiness?.hydration_details || '',
    home_cooling: responseData.fire_heat_readiness?.home_cooling ?? 0,
    home_cooling_details: responseData.fire_heat_readiness?.home_cooling_details || '',
    multiple_exit_points: responseData.fire_heat_readiness?.multiple_exit_points ?? 0,
    exit_points_details: responseData.fire_heat_readiness?.exit_points_details || '',
    identify_fire_risk: responseData.fire_heat_readiness?.identify_fire_risk ?? 0,
    fire_risk_details: responseData.fire_heat_readiness?.fire_risk_details || '',
    can_evacuate_independently: responseData.fire_heat_readiness?.can_evacuate_independently ?? 0,
    evacuate_independently_details: responseData.fire_heat_readiness?.evacuate_independently_details || '',
    support_from_family_or_neighbour: responseData.fire_heat_readiness?.support_from_family_or_neighbour ?? 0,
    support_from_family_or_neighbour_details: responseData.fire_heat_readiness?.support_from_family_or_neighbour_details || '',


    // Storm & Flooding Readiness
    storm_home_preparation_support: responseData.storm_flooding?.storm_home_preparation_support ?? 0,
    storm_home_preparation_details: responseData.storm_flooding?.storm_home_preparation_details  || '',
    storm_multiple_exit_points: responseData.storm_flooding?.storm_multiple_exit_points ?? 0,
    storm_multiple_exit_points_details: responseData.storm_flooding?.storm_multiple_exit_points_details || '',
    identify_flood_risk: responseData.storm_flooding?.identify_flood_risk ?? 0,
    identify_flood_risk_details: responseData.storm_flooding?.identify_flood_risk_details || '',
    storm_can_evacuate_independently: responseData.storm_flooding?.storm_can_evacuate_independently ?? 0,
    storm_evacuate_independently_details: responseData.storm_flooding?.storm_evacuate_independently_details || '',
    storm_support_from_family_or_neighbour: responseData.storm_flooding?.storm_support_from_family_or_neighbour ?? 0,
    storm_support_from_family_or_neighbour_details: responseData.storm_flooding?.storm_support_from_family_or_neighbour_details || '',


    // Telecommunication Outages Readiness
    independent_leave_home: responseData.telecommunication_outage?.independent_leave_home ?? 0,
    independent_leave_home_details: responseData.telecommunication_outage?.independent_leave_home_details || '',
    has_support_checkin: responseData.telecommunication_outage?.has_support_checkin ?? 0,
    has_support_checkin_details: responseData.telecommunication_outage?.has_support_checkin_details || '',
    welfare_check_required: responseData.telecommunication_outage?.welfare_check_required ?? 0,
    welfare_check_required_details: responseData.telecommunication_outage?.welfare_check_required_details || '',


    // Power Outages Readiness
    has_medical_equipment: responseData.power_outage?.has_medical_equipment ?? 0,
    has_backup_power: responseData.power_outage?.has_backup_power ?? 0,
    backup_power_details: responseData.power_outage?.backup_power_details || '',
    registered_life_support: responseData.power_outage?.registered_life_support ?? 0,
    life_support_hours_supply: responseData.power_outage?.life_support_hours_supply || '',
    life_support_provider: responseData.power_outage?.life_support_provider || '',
    power_independent_leave_home: responseData.power_outage?.power_independent_leave_home ?? 0,
    power_independent_leave_home_details: responseData.power_outage?.power_independent_leave_home_details || '',
    power_has_support_checkin: responseData.power_outage?.power_has_support_checkin ?? 0,
    power_has_support_checkin_details: responseData.power_outage?.power_has_support_checkin_details || '',
    power_welfare_check_required: responseData.power_outage?.power_welfare_check_required ?? 0,
    power_welfare_check_required_details: responseData.power_outage?.power_welfare_check_required_details || '',


    // End of Life & Advanced Care Planning
    receiving_palliative_care: responseData.end_of_life_advanced_care_planning?.receiving_palliative_care ?? 0,
    receiving_palliative_care_details: responseData.end_of_life_advanced_care_planning?.receiving_palliative_care_details || '',
    support_to_initiate_palliative_care: responseData.end_of_life_advanced_care_planning?.support_to_initiate_palliative_care ?? 0,
    support_to_initiate_palliative_care_details: responseData.end_of_life_advanced_care_planning?.support_to_initiate_palliative_care_details || '',
    has_advanced_care_plan: responseData.end_of_life_advanced_care_planning?.has_advanced_care_plan ?? 0,
    advanced_care_plan_details: responseData.end_of_life_advanced_care_planning?.advanced_care_plan_details || '',
    support_to_complete_advanced_care_plan: responseData.end_of_life_advanced_care_planning?.support_to_complete_advanced_care_plan ?? 0,
    support_to_complete_advanced_care_plan_details: responseData.end_of_life_advanced_care_planning?.support_to_complete_advanced_care_plan_details || '',
    has_dnr: responseData.end_of_life_advanced_care_planning?.has_dnr ?? 0,
    dnr_details: responseData.end_of_life_advanced_care_planning?.dnr_details || '',

  };
}
