export const supportPlanSteps = [
  { key: 'SupportPlan', label: 'Support Plan' },
  { key: 'Approval', label: 'Approval' },
  { key: 'Representatives', label: 'Representatives' },
  { key: 'CarePartner', label: 'Care Partner' },
  { key: 'KeepInTouch', label: 'Keep In Touch' },
  {key: 'NonResponsive', label: 'Non Responsive'},
  {key: 'ParticipantDetail', label: 'Participant Details'},
  {key: 'ContactDetail', label: 'Contact Details'},
  {key: 'SecondaryContactDetail', label: 'Secondary Detials'},
  {key: 'SupportFunding', label: 'Funding'},
  {key: 'SupportPlanServices', label: 'Support Plan Services'},
  {key: 'EmployeeMatchingNeeds', label: 'Employee Matching Needs'},
  {key: 'SupportPlanMyGoals', label: 'My Goals'},
  {key: 'LivingArrangements', label: 'Living Arrangements'},
  {key: 'CulturalDiversities', label: 'Cultural Diversities'},
  {key: 'GeneralHealth', label: 'General Health'},
  {key: 'MedicationManagement', label: 'Medication Management'},
  {key: 'MobilityTransfers', label: 'Mobility Transfers'},
  {key: 'FallsRisks', label: 'Falls Risks'},
  {key: 'Cognitions', label: 'Cognitions'},
  {key: 'BehaviourSupports', label: 'Behaviour Supports'},
  {key: 'PersonalCare', label: 'Personal Care'},
  {key: 'Continences', label: 'Continences'},
  {key: 'Visions', label: 'Visions'},
  {key: 'Hearings', label: 'Hearings'},
  {key: 'SkinConditions', label: 'Skin Conditions'},
  {key: 'Dietaries', label: 'Dietaries'},
  {key: 'HomeMaintenances', label: 'Home Maintenances'},
  {key: 'SocialConnections', label: 'Social Connections'},
  {key: 'PainManagement', label: 'Pain Management'},
  {key: 'FinancialSupport', label: 'Financial Support'},
  {key: 'InformalSupports', label: 'Informal Supports'},
  {key: 'EmergencyReadiness', label: 'Emergency Readiness'},
  {key: 'FireHeatReadiness', label: 'Fire & Heat Readiness'},
  {key: 'StormFlooding', label: 'Storm & Flooding Readiness'},
  {key: 'TelecommunicationOutages', label: 'Telecommunication Outages Readiness'},
  {key: 'PowerOutages', label: 'Power Outages Readiness'},
  {key: 'EndOfLifeAdvancedCare', label: 'EndOfLifeAdvancedCare'},
];