const supportPlanFormData = {
    //support plan
    effective_date: '',
    review_date: '',
    confirmation_date: '',
    developed_by: '',
    invited_but_not_participated: '',
    submit_final: 0,
    form_status: '',

    //approval
    participant_name: '',
    date_of_approval: '',
    signature: '',

    //respresentative
    support_representative_name: '',
    role: '',
    date_of_approval_representative: '',

    //care partner
    care_partner_name: '',
    care_partner_role: '',
    care_partner_contact_phone: '',
    care_partner_email: '',

    //keep in touch
    need_help_to_communicate: 0,
    type_of_difficulty: '',
    contact_first_instance: 0,
    details: '',
    language_spoken: '',
    use_nrs: 0,
    require_interpreter: 0,
    written: '',
    verbal: '',
    schedule_change_notification: '',
    interpreter_arrangement: '',
    financial_statement_method: '',
    feedback_survey_method: '',
    marketing_material_method: '',
    preferred_communication_method: '',
    join_cab: 0,

    // non responsive
    telephone_home_or_mobile: 0,
    telephone_details: '',
    contact_emergency_contact: 0,
    emergency_contact_details: '',
    access_spare_key: 0,
    enter_home_with_spare_key: 0,
    spare_key_details: '',
    contact_other_persons: 0,
    other_persons_details: '',
    contact_police_if_no_key: 0,
    police_contact_details: '',
    access_key_lock: 0,
    key_lock_code: '',
    key_lock_details: '',

    // participant detail

    first_name: '',
    surname: '',
    preferred_name: '',
    date_of_birth: '',
    country_of_birth: '',
    identify_as_aboriginal_or_torres_strait: 0,
    gender: '',


    // contact details
    phone: '',
    address: '',
    is_rural_area: 0,
    mailing_address: '',
    email: '',

    //secondary contact details

    secondary_role: '',
    secondary_phone: '',
    secondary_email: '',
    secondary_address: '',
    secondary_best_time_to_contact: '',
    secondary_is_mac_registered: 0,
    secondary_list_documents: '',
    secondary_legal_documentation_stored: 0,
    secondary_date_legal_orders_end: '',
    secondary_participants_agreed_contact: 0,
    secondary_participants_agreed_contact_date: '',
    secondary_decision_making_approval_for: '',

    //funnding
    aged_care_id: '',
    pension_status: '',
    pension_card_details: '',
    card_number: '',
    card_expiry: '',
    approved_funding_level: '',
    awaiting_package_upgrade: 0,
    upgrade_details: '',
    has_chsp_referral_codes: 0,
    chsp_referral_details: '',
    war_veteran_or_widow: 0,
    dva_number: '',
    medicare_number: '',
    private_health_insurance: '',
    hcp_funding_level: '',
    has_companion_card: 0,


    cultural_considerations: '',
    specific_training_required: '',
    common_interests: '',


    reside_in: '',
    reside_with: '',
    home_safety_assessment_date: '',
    is_home_suitable: 0,
    home_suitable_details: '',
    at_risk_of_homelessness: 0,
    homelessness_details: '',


    // Cultural Diversities
    is_lgbti: 0,
    lgbti_details: '',
    is_separated_family: 0,
    separated_family_details: '',
    has_cultural_events: 0,
    cultural_events_details: '',
    has_past_events: 0,
    past_events_details: '',
    has_non_disclosure_items: 0,
    non_disclosure_details: '',


    // General Health
    
    gp_visit_frequency: '',
    admitted_hospital_last12months: 0,
    admitted_hospital_details: '',
    preferred_hospital: 0,
    preferred_hospital_details: '',
    diagnosis_medication_conditions: '',
    previous_surgeries: '',
    has_allergies: 0,
    allergy_details: '',
    health_impact_scale: 0,
    painful_day_to_day: 0,
    painful_day_to_day_details: '',
    weight_loss_last3months: 0,
    weight_loss_details: '',
    nutritional_concerns: 0,
    nutritional_concerns_details: '',
    current_weight: '',
    annual_vaccinations: 0,
    annual_vaccination_details: '',
    last_influenza_vaccine: '',
    last_covid19_vaccine: '',
    last_pneumonia_vaccine: '',
    sleep_difficulties: 0,
    sleep_difficulties_details: '',
    sleep_routine: '',
    sleep_routine_worries: 0,
    sleep_routine_worries_details: '',
    alcohol_smoke_drug_use: 0,
    alcohol_smoke_drug_details: '',
    alcohol_smoke_drug_worries: 0,
    alcohol_smoke_drug_worries_details: '',
    referral_required: 0,
    referral_required_details: '',


    // Medication Management
    takes_regular_medications: 0,
    medication_details: '',
    medication_form: '',
    medication_packaging: '',
    medications_locked: 0,
    medications_locked_details: '',
    specific_storage_requirements: '',
    scheduled_4_or_8_medications: 0,
    scheduled_medications_details: '',
    chemical_restraint_medications: 0,
    takes_more_than_prescribed: 0,
    takes_more_than_prescribed_details: '',
    at_risk_of_missing_medication: 0,
    missing_medication_details: '',
    able_to_explain_purpose: 0,
    last_medication_review_date: '',
    medication_collection_delivery_details: '',
    needs_support_with_medication: 0,
    support_with_medication_details: '',
    medication_management_worries: 0,
    medication_management_worries_details: '',
    medication_service_required: 0,
    support_worker_prompt: 0,



    // Mobility & Transfers
    can_walk_independently: 0,
    walk_independently_details: '',
    needs_transfer_support: 0,
    primary_equipment_used: '',
    can_climb_stairs: 0,
    climb_stairs_details: '',
    has_stairs_at_home: 0,
    stairs_at_home_details: '',
    can_transfer_self: 0,
    can_transfer_in_other_envs: 0,
    uses_bed_pole_or_rails: 0,
    bed_pole_prescribed_by_ot: 0,
    can_access_places_outside_walking_distance: 0,
    access_places_details: '',
    safe_to_mobilise_in_yard: 0,
    mobilise_yard_details: '',
    community_access: '',
    drives: 0,
    medications_or_conditions_risk: 0,
    driving_risk_details: '',
    mobility_equipment: '',
    equipment_purchase_type: '',
    uses_four_wheel_walker: 0,
    four_wheel_walker_details: '',
    wheelchair_type: '',
    wheelchair_operation: '',
    wheelchair_ot_recommended: 0,
    can_charge_wheelchair: 0,
    last_wheelchair_service_date: '',
    can_carry_5kg: 0,
    carry_5kg_details: '',
    foot_problems: 0,
    foot_problems_details: '',
    mobility_worries: 0,
    mobility_worries_details: '',
    last_ot_assessment_date: '',
    new_ot_referral_required: 0,
    demmi_assessment_required: 0,
    demmi_assessment_result: '',


    // Falls Risks
    recent_falls: 0,
    recent_falls_details: '',
    strategies_to_reduce_risk: 0,
    strategies_details: '',
    has_safety_pendant: 0,
    safety_pendant_details: '',
    worried_about_falling: 0,
    worried_details: '',
    referral_falls_clinic: 0,
    referral_falls_clinic_details: '',
    referral_ot: 0,
    fallrisk_referral_ot_details: '',
    referral_physio: 0,
    referral_physio_details: '',


    // Cognitions
    cognitive_concerns: 0,
    cognitive_concerns_details: '',
    diagnosis_dementia: 0,
    diagnosis_dementia_details: '',
    capable_of_decisions: 0,
    capable_of_decisions_details: '',
    has_power_of_attorney: 0,
    power_of_attorney_details: '',
    becomes_confused: 0,
    becomes_confused_details: '',
    experienced_delirium: 0,
    experienced_delirium_details: '',
    anxious_or_worry: 0,
    anxious_or_worry_details: '',
    short_term_memory_loss: 0,
    short_term_memory_loss_details: '',
    long_term_memory_loss: 0,
    long_term_memory_loss_details: '',
    atsi_kica_cog_required: 0,
    atsi_kica_cog_file: '',
    atsi_kica_carer_required: 0,
    atsi_kica_carer_file: '',
    gpcog_required: 0,
    gpcog_file: '',
    health_literacy_support: 0,
    health_literacy_support_details: '',
    gds_required: 0,
    gds_file: '',
    referral_geriatrician: 0,
    referral_geriatrician_details: '',
    referral_psychologist: 0,
    referral_psychologist_details: '',
    referral_psychiatrist: 0,
    referral_psychiatrist_details: '',

    // Behaviour Supports
    feeling_agitation: 0,
    feeling_agitation_details: '',
    delusions_hallucinations: 0,
    delusions_hallucinations_details: '',
    personality_changes: 0,
    personality_changes_details: '',
    wandering_purpose: 0,
    wandering_purpose_details: '',
    absconding_concerns: 0,
    absconding_concerns_details: '',
    verbal_threats: 0,
    verbal_threats_details: '',
    physical_assault: 0,
    physical_assault_details: '',
    restrictive_interventions: 0,
    restrictive_interventions_details: '',
    restrictive_physical: 0,
    restrictive_approved_by_practitioner: 0,
    restrictive_practitioner_details: '',
    current_strategies: '',
    referral_positive_behaviour_practitioner: 0,
    referral_positive_behaviour_practitioner_details: '',
    behaviour_support_plan_required: 0,
    behaviour_support_plan_expiry: '',
    
    // Personal Cares
    support_daily_personal_care: 0,
    daily_personal_care_details: '',
    support_showering: 0,
    showering_type: '',
    showering_details: '',
    personal_care_routine: '',
    support_dressing: 0,
    dressing_details: '',
    dressing_routine: '',
    equipment_in_bathroom: 0,
    equipment_details: '',
    support_shaving: 0,
    shaving_details: '',
    support_haircuts: 0,
    haircuts_details: '',
    task_at_home: 0,
    wears_dentures: 0,
    dentures_details: '',
    support_teeth_brushing: 0,
    teeth_brushing_details: '',
    ot_bathroom_assessment: 0,
    ot_assessment_type: '',
    ot_assessment_details: '',
    referral_ot_required: 0,
    plancare_referral_ot_details: '',

    // Continences
    identified_needs: 0,
    identified_needs_details: '',
    identify_toilet_needs: 0,
    identify_toilet_needs_details: '',
    require_prompting: 0,
    require_prompting_details: '',
    wears_continence_aids: 0,
    continence_aids_details: '',
    ruis_required: 0,
    ruis_details: '',
    rfis_required: 0,
    rfis_details: '',
    funding_for_products: 0,
    funding_for_products_details: '',
    nurse_assessment: 0,
    nurse_assessment_details: '',
    worry_about_continence: 0,
    worry_about_continence_details: '',


    // Visions
    wears_glasses_or_contacts: 0,
    glasses_or_contacts_type: '',
    vision_when_worn: '',
    last_optometrist_appointment: '',
    vision_worry: 0,
    vision_worry_details: '',

    // Skin Conditions
    has_skin_condition: 0,
    skin_condition_type: '',
    impacts_daily_activities: 0,
    impact_date: '',
    pain_discomfort_level: '',
    pain_level_score: 0,
    management_strategies: '',
    skin_condition_worry: 0,
    worry_date: '',
    referral_nursing_required: 0,
    referral_nursing_date: '',


    // Dietaries
    intolerances: 0,
    intolerances_details: '',
    dysphagia_concerns: 0,
    dysphagia_details: '',
    speech_pathologist_recommendations: 0,
    iddsi_food_category: '',
    iddsi_liquid_category: '',
    prepares_meals: 0,
    prepares_meals_details: '',
    needs_meal_support: 0,
    meal_support_details: '',
    diet_meets_needs: 0,
    diet_meets_needs_details: '',
    needs_cutting_support: 0,
    cutting_support_details: '',
    needs_feeding_support: 0,
    feeding_support_details: '',
    dietician_referral_required: 0,
    dietician_referral_details: '',
    needs_shopping_support: 0,
    shopping_support_details: '',

    // Pain Management
    ongoing_pain: 0,
    pain_details: '',
    pain_location: '',
    pain_frequency: '',
    pain_scale: 0,
    supported_for_pain: 0,
    supported_pain_details: '',
    pain_management_strategies: '',
    abbey_pain_scale_required: 0,
    pain_worry: 0,
    pain_worry_details: '',
    

    // Social Connections

    feels_lonely: 0,
    feels_lonely_details: '',
    has_informal_supports: 0,
    informal_supports_details: '',
    wants_more_community_engagement: 0,
    community_engagement_details: '',
    wants_support_for_community_engagement: 0,
    support_for_community_engagement_details: '',
    needs_community_access_support: 0,
    community_access_support_details: '',
    has_taxi_card: 0,
    taxi_card_details: '',
    interested_in_visitors_program: 0,
    visitors_program_details: '',
    has_hobbies_activities: 0,
    hobbies_activities_details: '',
    needs_duke_index: 0,
    duke_index_details: '',
    social_connections_needs_feeding_support: 0,
    social_connections_feeding_support_details: '',
    social_connections_wants_dietician_referral: 0,
    social_connections_dietician_referral_details: '',
    social_connections_needs_shopping_support: 0,
    social_connections_shopping_support_details: '',

    // Home Maintenances

     needs_domestic_assistance: 0,
    domestic_assistance_type: '',
    domestic_assistance_details: '',
    needs_help_with_cleaning_products: 0,
    cleaning_products_details: '',
    needs_garden_support: 0,
    garden_support_details: '',
    trouble_navigating_at_night: 0,
    navigating_at_night_details: '',
    home_maintenance_worries: 0,
    home_maintenance_worries_details: '',
    last_home_safety_assessment: '',
    home_safety_focus_areas: '',

    // Financial Support
    financial_has_power_of_attorney: 0,
    financial_power_of_attorney_details: '',
    has_access_to_money: 0,
    access_to_money_details: '',
    at_risk_of_abuse: 0,
    risk_of_abuse_details: '',
    needs_support_for_bills: 0,
    support_for_bills_details: '',
    not_enough_money: 0,
    not_enough_money_details: '',
    support_financial_counsellor: 0,
    financial_counsellor_details: '',
    support_government_initiatives: 0,
    government_initiatives_details: '',



    // Informal Supports
    is_primary_caregiver: 0,
    primary_caregiver_details: '',
    receiving_help: 0,
    receiving_help_details: '',
    carer_lives_with_you: 0,
    carer_lives_with_you_details: '',
    carer_receives_pension: 0,
    carer_pension_details: '',
    factors_affecting_care: 0,
    factors_affecting_care_details: '',
    caregiver_strain_index_required: 0,
    carer_gateway_referral: 0,
    carer_gateway_referral_details: '',
    primary_caregiver_receives_allowance: 0,

    // Emergency Readiness
    emergency_at_risk_of_abuse: 0,
    abuse_details: '',
    opan_referral_required: 0,
    opan_referral_details: '',
    risk_of_declining_services: 0,
    declining_services_details: '',
    neglect_indicators: 0,
    neglect_indicators_details: '',
    emergency_accessible: 0,
    emergency_accessible_details: '',
    emergency_support_available: 0,
    emergency_support_details: '',
    vpr_required: 0,
    vpr_details: '',


    // Fire & Heat Readiness
    home_preparation_support: 0,
    home_preparation_details: '',
    hydration_access: 0,
    hydration_details: '',
    home_cooling: 0,
    home_cooling_details: '',
    multiple_exit_points: 0,
    exit_points_details: '',
    identify_fire_risk: 0,
    fire_risk_details: '',
    can_evacuate_independently: 0,
    evacuate_independently_details: '',
    support_from_family_or_neighbour: 0,
    support_from_family_or_neighbour_details: '',

    storm_home_preparation_support: 0,
    storm_home_preparation_details: '',
    storm_multiple_exit_points: 0,
    storm_multiple_exit_points_details: '',
    identify_flood_risk: 0,
    identify_flood_risk_details: '',
    storm_can_evacuate_independently: 0,
    storm_evacuate_independently_details: '',
    storm_support_from_family_or_neighbour: 0,
    storm_support_from_family_or_neighbour_details: '',

    // Telecommunication Outages Readiness
    independent_leave_home: 0,
    independent_leave_home_details: '',
    has_support_checkin: 0,
    has_support_checkin_details: '',
    welfare_check_required: 0,
    welfare_check_required_details: '',


    // End of Life & Advanced Care Planning
    receiving_palliative_care: 0,
    receiving_palliative_care_details: '',
    support_to_initiate_palliative_care: 0,
    support_to_initiate_palliative_care_details: '',
    has_advanced_care_plan: 0,
    advanced_care_plan_details: '',
    support_to_complete_advanced_care_plan: 0,
    support_to_complete_advanced_care_plan_details: '',
    has_dnr: 0,
    dnr_details: '',


}
export default supportPlanFormData;